### ISSUE TITLE
New Policies

### ISSUE THREAD

**Issue by dkwiebe** [cloudveiltech/CloudVeilMessenger#12]
It would be nice to have a whitelisted stickers and users just like channels, groups, and bots.  

disable_stickers - If this is set we don't allow any stickers.
manage_users - If this is set then we handle users just like channels and bots.

**Comment by dkwiebe** [comment]
@patriciy The management interface is mostly in place for this.  I'll have a bit of finetuning to do once you start sending me data.

**Comment by patriciy** [comment]
Commit a281af7240be251ba7b9f8990437e7d955eded27 in master
