### ISSUE TITLE
Change button to toggle video/voice recordings

### ISSUE THREAD

**Issue by dkwiebe** [cloudveiltech/CloudVeilMessenger#13]
On the bottom right hand side of the input screen there's a button you press and hold to send audio or video.  I'd like that changed so that it's only a voice recording button and so that clicking on it does not change it to a video recorder.

**Comment by dkwiebe** [comment]
This could be controlled by the "input_toggle_voice_video" server setting.

**Comment by patriciy** [comment]
5ac52db033f1fb844e98e111b8645d27f256dbe8
implemented here
