### ISSUE TITLE
Blocked camera crashes app on Samsungs

### ISSUE THREAD

**Issue by thetmtech** [cloudveiltech/CloudVeilMessenger#14]
If the camera is disabled at the system level by a device admin app, the app will crash with the warning "security policy prevents use of camera."

**Comment by dkwiebe** [comment]
@patriciy Can you take a look at this?

**Comment by thetmtech** [comment]
I encountered this issue on an LG M150 today as well.

**Comment by patriciy** [comment]
All in all issue is that on Samsung devices Camera.open causes App's process to be killed. 
Camera2 API seems to throw exception (as expected) though. Also disabled camera could be checked over Device Policy Manager. Implemented both checks.

Fixed in 416029afb0112597d3476b75305368a35ea31f54
