### ISSUE TITLE
Unable to seek to position, no playback position indicator in voicenote playback

### ISSUE THREAD

**Issue by montesound** [cloudveiltech/CloudVeilMessenger#18]
4.6.0 (962) can scroll position, 4.6.1 (964) cannot. Also, 964 does not show position while playing.

**Comment by patriciy** [comment]
The issue is inside OGG native player. We didn't touch it.
it can't recognize file size. 
4.6.0 behaves the same for me.

**Comment by patriciy** [comment]
That was an issue inside NDK
Implemented here 9ce9d4ba934f3ba09b9372dc751c4507dbe491ad
