### ISSUE TITLE
Allow speed up audio play

### ISSUE THREAD

**Issue by dkwiebe** [cloudveiltech/CloudVeilMessenger#25]
We need to be able to have users play audio faster than it is recorded.

**Comment by dkwiebe** [comment]
This could just go up to 1.5 unless we can work with the voice pitch as they get too high to be understandable.  Telegram has added support for this in their latest version so maybe we can see how they did it.

**Comment by patriciy** [comment]
There's x2 speedup in last version (4.9+)
