### ISSUE TITLE
Adaptive Icon needed

### ISSUE THREAD

**Issue by terry7577** [cloudveiltech/CloudVeilMessenger#26]
Let me know what you need for graphics and I'll upload them, as I have them all in vector format. If I understand it right you'll need the background in a separate layer?

![image](https://user-images.githubusercontent.com/33460552/44673282-4fbb9380-a9e8-11e8-8b2a-915c1d74bd25.png)

**Comment by terry7577** [comment]
![cvm_logo_background](https://user-images.githubusercontent.com/33460552/44948138-ba4c4500-add5-11e8-9676-caf36c7ada0a.png)
![cvm_logo_foreground](https://user-images.githubusercontent.com/33460552/44948139-ba4c4500-add5-11e8-8b98-f5ba01166a28.png)

**Comment by terry7577** [comment]
[CVM_Logo_Foreground.zip](https://github.com/cloudveiltech/CloudVeilMessenger/files/2342539/CVM_Logo_Foreground.zip)

**Comment by terry7577** [comment]
Even just updating the icon would be a step ahead, we could work with the adaptive part later. I'd like to remove that small text.

**Comment by dkwiebe** [comment]
@patriciy Could you create an update with the files that @terry7577 included as the icons?
