### ISSUE TITLE
Stickers partially available

### ISSUE THREAD

**Issue by dkwiebe** [cloudveiltech/CloudVeilMessenger#27]
When you enter an emoticon on the keyboard then a list of stickers that you could select comes up.  It would be nice to have this removed on devices where stickers are turned off.

**Comment by dkwiebe** [comment]
In secret chats we're currently able to send stickers using this system.  Also, in secret chats stickers are showing when sent or received.

**Comment by patriciy** [comment]
91e51fe7c49f86841d2f080f965f6ef811412f12
