### ISSUE TITLE
CloudVeil branding on invite link

### ISSUE THREAD

**Issue by sirsoweird** [cloudveiltech/CloudVeilMessenger#3]
Using the invite friends link sends a message via another app; the message contents refer to the telegram.org download link and the Telegram name.

**Comment by sirsoweird** [comment]
https://github.com/cloudveiltech/CloudVeilMessenger/blob/master/TMessagesProj/src/main/res/values/strings.xml#L676

Looks like it's changed already, where can I get a new build?

**Comment by dkwiebe** [comment]
@sirsoweird This repo hasn't been building but should be buildable by the end of the weekend.
