### ISSUE TITLE
Remove Sensitive Permissions

### ISSUE THREAD

**Issue by dkwiebe** [cloudveiltech/CloudVeilMessenger#32]
Google has changed Play Store policies and we no longer get access to android.permission.RECEIVE_SMS and android.permission.READ_SMS just for account verification.  We need to remove these permission requirements from the app.

**Comment by patriciy** [comment]
This seems to be Play issue. 
- start creating a release with old version
- fill the "permission" form
- discard new release
- create new release with latest version only. Permission form didn't appear
