### ISSUE TITLE
Blocked channels and bots bypass

### ISSUE THREAD

**Issue by thetmtech** [cloudveiltech/CloudVeilMessenger#38]
Blocked channels and bots can be accessed by tapping the screen really fast before the blocked popup appears.

**Comment by terry7577** [comment]
Looks like nothing has been updated here for a few months, is it being followed?

Anyways, this has been fixed, except for the t.me links, for example https://t.me/gamee can be accessed this way but @gamee doesn't work.

**Comment by dkwiebe** [comment]
@terry7577 Yes, it should have been closed when the original issue was patched.  I've added a note in Trello for the t.me links and we'll get that patched.

**Comment by dkwiebe** [comment]
@terry7577 I missed posting back here earlier but I think this was patched some time ago.  Can you still bypass it?

**Comment by terry7577** [comment]
t.me links are now instantly blocked for me.
