### ISSUE TITLE
"Contact joined Cloudveil Messenger" notifications when switched off

### ISSUE THREAD

**Issue by brianjohnpenner** [cloudveiltech/CloudVeilMessenger#39]
I am still getting notifications about new contacts joining CVM/Telegram when I have that switched off in settings.

**Comment by brianjohnpenner** [comment]
May be related to issue #36?

**Comment by dkwiebe** [comment]
@cvbrian Is this still happening to you?  I haven't duplicated it.

**Comment by brianjohnpenner** [comment]
I got one a couple of weeks ago and I haven't changed anything since then. If I'm the only one that's running into this it's not a big deal. It doesn't happen very often.

**Comment by brianjohnpenner** [comment]
I'm just seeing that I'm getting them on all my devices so likely a Telegram issue.
