### ISSUE TITLE
Webservice to provide policies

### ISSUE THREAD

**Issue by dkwiebe** [cloudveiltech/CloudVeilMessenger#5]
Build a server based system that controls the following options per user:

1. Allowed / Disallowed groups, bots, and channels.

This would allow normal usage but would simplify the process for reporting and blocking unacceptable content.  bots and gorups could be either whitelisted or blacklisted.  The app would have to send a list of groups, bots, and channels up to the server and would receive a list back of those it was not allowed to contact.

2. Minimum length of secret chats.

This would allow the benefits received from secret chats but the server could send back the minimum length that the app will allow setting a secret chat.

3. We need the app to display a popup like this when it first starts:

CloudVeil Messenger uses a server based system to control access to Bots, Channels, and Groups and other policy rules.  This is used to block unacceptable content.  Your Telegram id and list of channels, bots, and groups will be sent to our system to allow this to work.  We do not have access to your messages themselves.

**Sample Communication**

HTTP Post to Management URL:
JSON Body containing Telegram ID and UserID as well as arrays of bots, channels and groups.  The response will contain the same list of bots, channels, and groups with true or false for each record.  If the response for an entity is true then access is allowed.  
It will also contain the following variables:
"secret_chat" If "true" then they're allowed.  If "false" then we block secret chats.
"secret_chat_minimum_length"  I'm not sure how the values should be returned but this will be the minimum length that we can set for a secret chat.

**Comment by dkwiebe** [comment]
At least to begin with we will be controlling the policies globally and not per user.

**Comment by patriciy** [comment]
Started in 17d71026361f0e599b6a37ab2ac439183d734878
Finished in 6a04c76bf29994686e9e5a49df428c273ab21a11
