### ISSUE TITLE
Branding Problem

### ISSUE THREAD

**Issue by dkwiebe** [cloudveiltech/CloudVeilMessenger#8]
The word "Telegram" shows up in the title bar of the app.  It's just above the list of contacts.

**Comment by patriciy** [comment]
What should it be instead of "Telegram" ?

**Comment by dkwiebe** [comment]
It should be "CloudVeil Messenger"

**Comment by patriciy** [comment]
The problem is Telegram has remote localizations. 
And for "en" locale it uses remote localization.

I copy-pasted en values to local storage and forced use local value for "AppName" key. 

All in all may be it could be good idea to disable/restrict remote localization.

**Comment by patriciy** [comment]
Pushed to branding_locale_fixes
Commit: 1a6e2ee8c80ad2742e79b0d01a15676b460e34cd
