### ISSUE TITLE
Create Telegram Client

### ISSUE THREAD

**Issue by dkwiebe** [cloudveiltech/CloudVeilMessenger#9]
It would be nice to have a server based Telegram client that we could send public channel, bot, and public group names to.  It could then get the metadata about the item and pass it up to our API where we can make a categorization decision about it.

This would allow us to somewhat automatically build our list of banned channels and groups without one of us having to visit it on our devices.

**Comment by df8Ojw** [comment]
Maybe I'm not understand the process ~ but wouldn't that make it inherently slower than the currently method?
~ Dean

**Comment by dkwiebe** [comment]
I was envisioning a program that we parse the contents of a site like tchannels.me, feed them into it, and have it populate our list.  So far we're planning on operate in whitelist mode but if our list was complete enough we'd be able to consider switching to blacklists.

**Comment by dkwiebe** [comment]
We can scrape the data off of the web like: https://t.me/telegram but that doesn't give us the ids we need to block them.

**Comment by dkwiebe** [comment]
I have built (using existing libraries) a Telegram client that can run in cron jobs to collect data on users, channels, groups, and bots.  It is supposed to be a fully functional Telegram client but I don't have that all figured out yet. We could use this script for Accountability Partner notifications without requiring the user to contact us first.  

We'll still use the current blocking process but this is intended to make it easier for our support staff to whitelist channels.
